#include <stdio.h>

//	*FUNTION THAT GETS THE POINTER OF A CHAR AND RETURNS THE ADDRESS OF THE "STATIC" INT ARRAY
int * get_comma_positions( char * string ) {

	static int commas[32];//	*ONLY STATIC VALUES CAN GO OUTSIDE THE FUNCTION
	int a = 0;
	int b = 0;
	
	for ( a = 0; a < 64; a++ ) {//	*FOR CYCLE...TAKE ELEMENT BY ELEMENT OF THE CHAR ARRAY...
		if (  string[a] == ',' ) {//	*IF THE A-TH ELEMENT IS A COMMA THEN...
				commas[b] = a;//	*SAVE THE POSITION OF THE COMMA ON THE STRING[] IN THE COMMA[]...
				b++;//	*INCREMENT B TO THE NEXT SAVING POSITION OF THE COMMA[]...
				printf( "comma found at position: %i\n", a );//	*PRINT THE POSITION OF THE COMMA FOUND...
		}
	}
	return commas;//	*RETURNS THE ADDRESS OF THE COMMA[]...
}

int main( void ) {

	int a = 0;
	char line[64] = "Edgardo, Leno, Tinoquina, Barjute, Kelkul, Pluto, Charon, Mars";//	*LINE TO BE ANALYZED...
	int * pointer_to_array;//	*DECLARATION OF A POINTER TO AN INT...

	pointer_to_array = get_comma_positions( line );//	*SAVE THE ADDRESS RETURNED BY THE FUNCTION...
	printf( "Address of the Pointer Variable returned is: %p\n", pointer_to_array );
	printf( "{ " );//	*HERE BEGINS THE CODE TO PRESENT THE FORMATTED TEXT EXIT...
	for ( a = 0; a < 32; a++ ) {//	*FOR CYCLE...TAKE ELEMENT BY ELEMENT OF THE ARRAY...
		if ( *(pointer_to_array + a) != 0 ) {//	*IF THE VALUE POINTED IS DIFFERENT FROM 0, THEN...
			if ( a == 0 )//	*ARE WE IN THE FIRST ELEMENT OF THE ARRAY...
				printf( "%i", *(pointer_to_array + a) );//	*THEN FURMATTED TEXT MUST BE...
			else
				printf( ", %i", *(pointer_to_array + a) );//	*THE SHOULD BE THIS ONE...
		}
		else
			a = 32;//	*THIS ENDS THE FOOR LOOP...
	}
	printf( " }\n" );//	*THIS PRINT THE LAST CHARACTERS OF THE FORMATED TEXT EXIT...
	return 0;
}
